FROM node

# Set environment to production
ENV NODE_ENV=production

WORKDIR /usr/src/app

# Only copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Copy the rest of your application
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the server using node
CMD [ "node", "app.js" ]